version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: stock-market-tracker-mongo
    ports:
      - "27017:27017"
    networks:
      - stock-marker-tracker

  postgres:
    image: postgres:14-alpine
    container_name: stock-market-tracker-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - stock-marker-tracker

  # TODO: create realm, user and roles with docker
#  keycloak:
#    image: keycloak/keycloak:17.0.0
#    container_name: stock-marker-tracker-keycloak
#    environment:
#      KEYCLOAK_DATABASE_HOST: stock-marker-tracker-postgres
#      KEYCLOAK_DATABASE_NAME: postgres
#      KEYCLOAK_DATABASE_USER: root
#      KEYCLOAK_DATABASE_PASSWORD: secret
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: password
#    ports:
#      - "8080:8080"
#    networks:
#      - stock-marker-tracker
#    depends_on:
#      - postgres
  keycloak:
    container_name: stock-market-tracker-keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    command:
      - start-dev
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/docker_volumes/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: stock-marker-tracker-postgres
      KEYCLOAK_DATABASE_NAME: postgres
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: secret
    depends_on:
      - postgres
    networks:
      - stock-marker-tracker

#  eureka:
#    container_name: eureka
#    build:
#      context: ./eureka
#      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"
#    networks:
#      - stock-marker-tracker
#
#  auth-service:
#    container_name: stock-market-tracker-auth-service
#    build:
#      context: ./auth-service
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - eureka
#      - keycloak
#    networks:
#      - stock-marker-tracker

#  portfolio-service:
#    container_name: stock-market-tracker-portfolio-service
#    build:
#      context: ./portfolio-service
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    depends_on:
#      - eureka
#    networks:
#      - stock-marker-tracker
      
networks:
  stock-marker-tracker:
    driver: bridge

volumes:
  postgres:
    driver: local